package com.zhao.mapp.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USERS.
 */
public class Users {

    private Long id;
    /** Not-null value. */
    private String loginname;
    private String username;
    private String md5password;
    private java.util.Date lastlogintime;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String loginname, String username, String md5password, java.util.Date lastlogintime) {
        this.id = id;
        this.loginname = loginname;
        this.username = username;
        this.md5password = md5password;
        this.lastlogintime = lastlogintime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLoginname() {
        return loginname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMd5password() {
        return md5password;
    }

    public void setMd5password(String md5password) {
        this.md5password = md5password;
    }

    public java.util.Date getLastlogintime() {
        return lastlogintime;
    }

    public void setLastlogintime(java.util.Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

}
